### PR TITLE
Some changes in the format of icons for iOS

### PR DESCRIPTION
**Pull request by pepibumur**
As @Caiopia suggested on [this PR](https://github.com/Shopify/ios/pull/12350):

- [x] Set the `template-rendering-intent` attribute to template.
- [x] Don't generate a Swift interface and let the client *(iOS repository)* do it to. That way we remove potential friction when upgrading Xcode versions.

### CODE REVIEW

**Comment by amrocha** [comment]
I'm not familiar enough with iOS so I have a few questions:
- Why does the xCode version matter?
- Why is generating the code for the interface here a problem? This seems really strange to me coming from JS where we have lots of external dependencies. Does the iOS team write *literally every single line* of code they run?
- Does apple just break stuff without deprecating it first?

**Comment by pepibumur** [comment]
> Why does the xCode version matter?

It shouldn't. I doubt Apple introduces breaking changes in the format of the catalog, and if they do, they compilation will likely fail.

> Why is generating the code for the interface here a problem? This seems really strange to me coming from JS where we have lots of external dependencies. Does the iOS team write literally every single line of code they run?

The thing is that the iOS build system is very static. You configure your build target to compile X swift files, and copy Y resources, and that can't be dynamically modified. Conversely Android, which uses Gradle, allows a more dynamic configuration, where plugins can participate in the build process.
iOS developers write most of the code, with the exception of some code that they generate using tools like [Rocky](https://github.com/shopify/shopify) or [SwiftGen](https://github.com/SwiftGen/SwiftGen). Those tools need to be run beforehand and the output, Swift files, need to be **manually added** to the project.
Coming from web, where tooling is way more advanced and flexible, this is like going years back in history.
Answering your question. Generating the Swift interface here has 2 downsides:
- If a new version of Swift comes out, introducing changes in the types the interface depends on, developers depend on this project updating the interface in order to update Swift on their end.
- There's some code generated in the interface that would clash with the interfaces that they generate. I solved this by changing the template a little bit but they don't quite like the idea.

> Does apple just break stuff without deprecating it first?

They do. The problem is what I mentioned above. Let's say we get the following interfaces.

```swift
// PolarisIcons.swift (from the gem)
typealias Image = UIImage
enum PolarisIcons {
  let bar = UIImage(named: "bar")
}


// Assets.swift (from the iOS repository)
typealias Image = UIImage
enum Asset {
  let foo = Image(named: "foo")
}
```

The lines that define the typealiases would clash at compilation time.

**Comment by pepibumur** [comment]
@amrocha / @kaelig I made this one tophattable too. You can run:

```
dev ios tophat https://github.com/Shopify/polaris-icons/pull/671
```

**Comment by kaelig** [comment]
That's amazing, @pepibumur!

Why do some icons have a fill in unexpected places?

```
rsvg-convert packages/polaris-icons-raw/icons/polaris/tools_major_monotone.svg -f pdf -o test.pdf
```
Renders this:
Screen Shot 2019-09-19 at 3 00 56 PM

But in the tophatted app, it looks like so:

Screen_Shot_2019-09-19_at_3_00_29_PM

**Comment by pepibumur** [comment]
@kaelig interesting. Which simulator are you using? This is what I'm getting

image

**Comment by kaelig** [comment]
I was running the tophat command using iPhone X, on the most recent iOS in the list. 

The issue I described with the Tools icon doesn't show in your screenshot. However, other icons are affected by a similar fill issue (for example: the gamepad icon, see https://polaris-icons.shopify.com/?icon=GamesConsoleMajor).

**Comment by pepibumur** [comment]
Isn't that expected? if I search for the icons, I see there are 2 versions of `toos_major`, monotone and twotone:

image

And the same for `games-console` icon:

image

**Comment by kaelig** [comment]
I see how this can be confusing. The black zone should be white instead. 

@amrocha can you pair with @pepibumur this week and go through the steps necessary to ensure two-tone icons render correctly?

**Comment by pepibumur** [comment]
> @amrocha can you pair with @pepibumur this week and go through the steps necessary to ensure two-tone icons render correctly?

I scheduled a call to pair with @amrocha next Monday.

**Comment by amrocha** [comment]
I don't really know why the icons are rendering like that. The only thing that could be causing it on our end is that we run a transform on fills for web browsers.

Until now, icons needed to be rendered in two contexts: the browser, and a design tool (Sketch before, now Figma)

Sketch/Figma don't support `currenColor`, a CSS property that we use to render icons that have white fills in the browser, so we run this code during the build process:
```js
const WHITE_REGEX = /^#fff(?:fff)?$/i;

replaceFill: {
  transform: (fill) => (WHITE_REGEX.test(fill) ? 'currentColor' : ''),
},
```

We replace all `#FFF` fills with `currentColor`. But you're manipulating the SVGs directly, so you should still have the original white fills.

I suspect this is either a problem in the conversion to PDF step, or an issue with the way iOS renders icons. Either way, I'm not too familiar with either, so I don't think I can help much, but if you want to pair on it I'll be available.

**Comment by kaelig** [comment]
Line 80 seems like it could be the culprit. The script should convert the raw SVGs, and from what I can see on line 80, the script is using the processed SVGs.

Hope this helps.

**Comment by kaelig** [comment]
I think I figured it out: tinting twotone icons in black leads to also tinting the white tones (not just the dark paths).

I opened a PR (with the `ios-fixes` branch as a base) to use raw icons as the source for generating PDFs, and exclude twotone icons from the build: https://github.com/Shopify/polaris-icons/pull/680

**Comment by pepibumur** [comment]
> I opened a PR (with the ios-fixes branch as a base) to use raw icons as the source for generating PDFs, and exclude twotone icons from the build: #680

Thanks for fixing it @kaelig. The PR looks good to me. I merged it to master and rebased it from here. Once you assert everything looks good, I think we can merge.

**Pull request merged**
